dist: trusty
sudo: off
language: python
services:
  - docker
install:
    - pip install pylint==1.9.5 flake8==3.5.0 requests wheel==0.30.0 -q
jobs:
  include:
    - stage: precheck
      env: PURPOSE='SourceStatic'
      script: ./scripts/ci/test_static.sh
      python: 3.6
    - stage: precheck
      env: PURPOSE='SourceStaticPy'
      script: python ./scripts/ci/test_static.py
      python: 3.6
    - stage: verify
      env: PURPOSE='IndexVerify'
      script: python ./scripts/ci/test_index.py -v
      python: 3.6
    - stage: verify
      env: PURPOSE='SourceTests'
      script: ./scripts/ci/test_source.sh
      python: 2.7
    - stage: verify
      env: PURPOSE='SourceTests'
      script: ./scripts/ci/test_source.sh
      python: 3.6
    - stage: verify
      env: PURPOSE='Load and Lint Modified Index Entries'
      script: ./scripts/ci/verify_modified_index.sh
      python: 3.6
    - stage: verify
      env: PURPOSE='IndexRefDocVerify'
      script: ./scripts/ci/test_index_ref_doc.sh
      python: 3.6
#    - stage: publish
#      script: |
#        docker run \
#          --rm \
#          -e TRAVIS_BUILD_ID=$TRAVIS_BUILD_ID \
#          -e TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG \
#          -e TRAVIS_COMMIT=$TRAVIS_COMMIT \
#          -e GH_TOKEN=$GH_TOKEN \
#          -e DOC_REPO_SLUG='MicrosoftDocs/azure-docs-cli' \
#          -e REPO_LOCATION=/repo \
#          -v $PWD:/repo \
#          mcr.microsoft.com/azure-cli-ext/ext-list-publisher:0.3.0
#      env: PURPOSE='SyncAvailableExtensionsDoc'
#      if: repo = Azure/azure-cli-extensions and branch = master and type = cron
  fast_finish: true
