dist: trusty
sudo: off
language: python
services:
  - docker
install:
    - pip install pylint flake8 requests -q
jobs:
  include:
    - stage: verify
      env: PURPOSE='SourceStatic'
      script: ./scripts/ci/test_static.sh
      python: 2.7
    - stage: verify
      env: PURPOSE='SourceStatic'
      script: ./scripts/ci/test_static.sh
      python: 3.6
    - stage: verify
      env: PURPOSE='SourceTests'
      script: ./scripts/ci/test_source.sh
      python: 2.7
    - stage: verify
      env: PURPOSE='SourceTests'
      script: ./scripts/ci/test_source.sh
      python: 3.6
    - stage: verify
      env: PURPOSE='IndexVerify'
      script: python ./scripts/ci/test_index.py -v
      python: 3.6
    - stage: verify
      env: PURPOSE='IndexRefDocVerify'
      script: ./scripts/ci/test_index_ref_doc.sh
      python: 3.6
    - stage: publish
      python: 3.6
      script: docker run --rm -e TRAVIS_BUILD_ID=$TRAVIS_BUILD_ID -e TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG -e TRAVIS_COMMIT=$TRAVIS_COMMIT -e GH_TOKEN=$GH_TOKEN -e DOC_REPO_SLUG='Azure/azure-docs-cli-python' -v $PWD:/repo derekbekoe/az-avail-ext-doc-sync:0.1.2
      env: PURPOSE='SyncAvailableExtensionsDoc'
      if: repo = Azure/azure-cli-extensions and branch = master and type = push
  fast_finish: true
  allow_failures:
    - env: PURPOSE='SourceTests'
