dist: trusty
sudo: off
language: python
install:
    - pip install pylint flake8 requests
jobs:
  include:
    - stage: verify
      env: PURPOSE='SourceStatic'
      script: ./scripts/ci/test_static.sh
      python: 2.7
    - stage: verify
      env: PURPOSE='SourceStatic'
      script: ./scripts/ci/test_static.sh
      python: 3.6
    - stage: verify
      env: PURPOSE='SourceTests'
      script: python ./scripts/ci/test_source.sh
      python: 2.7
    - stage: verify
      env: PURPOSE='SourceTests'
      script: python ./scripts/ci/test_source.sh
      python: 3.6
    - stage: verify
      env: PURPOSE='IndexVerify'
      script: python ./scripts/ci/test_integration.py -v
      python: 3.6
  allow_failures:
    - env: PURPOSE='SourceTests'
